ALTER TABLE IF EXISTS positions
    ADD COLUMN IF NOT EXISTS market_type VARCHAR(20) NOT NULL DEFAULT 'SPOT';

ALTER TABLE IF EXISTS positions
    ADD COLUMN IF NOT EXISTS leverage INTEGER NOT NULL DEFAULT 1;